### ISSUE TITLE
Error building 1.0.0 for aarch64

### ISSUE THREAD

**Issue by alucryd** [google/highway#937]
Hi guys, having trouble cross-building the latest release for aarch64 on x86_64, he's the build log:

```
ninja: Entering directory `build'
[1/10] Building CXX object CMakeFiles/hwy.dir/hwy/print.cc.o
[2/10] Building CXX object CMakeFiles/hwy.dir/hwy/targets.cc.o
[3/10] Building CXX object CMakeFiles/hwy.dir/hwy/aligned_allocator.cc.o
[4/10] Building CXX object CMakeFiles/hwy_list_targets.dir/hwy/tests/list_targets.cc.o
[5/10] Building CXX object CMakeFiles/hwy_test.dir/hwy/tests/test_util.cc.o
[6/10] Building CXX object CMakeFiles/hwy.dir/hwy/per_target.cc.o
FAILED: CMakeFiles/hwy.dir/hwy/per_target.cc.o 
/home/embybuilder/Buildbot/armv8/toolchain/bin/aarch64-emby-linux-gnu-g++ --sysroot=/home/embybuilder/Buildbot/armv8/toolchain/aarch64-emby-linux-gnu/sysroot -DHWY_STATIC_DEFINE -I/home/embybuilder/Buildbot/armv8/libhighway-armv8/build/highway-1.0.0 -march=armv8-a -mtune=generic -mno-outline-atomics -Os -pipe -fno-plt -I/home/embybuilder/Buildbot/armv8/staging/include -O3 -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -fmath-errno -fno-exceptions -MD -MT CMakeFiles/hwy.dir/hwy/per_target.cc.o -MF CMakeFiles/hwy.dir/hwy/per_target.cc.o.d -o CMakeFiles/hwy.dir/hwy/per_target.cc.o -c /home/embybuilder/Buildbot/armv8/libhighway-armv8/build/highway-1.0.0/hwy/per_target.cc
In file included from /home/embybuilder/Buildbot/armv8/libhighway-armv8/build/highway-1.0.0/hwy/highway.h:361,
                 from /home/embybuilder/Buildbot/armv8/libhighway-armv8/build/highway-1.0.0/hwy/per_target.cc:21,
                 from /home/embybuilder/Buildbot/armv8/libhighway-armv8/build/highway-1.0.0/hwy/foreach_target.h:125,
                 from /home/embybuilder/Buildbot/armv8/libhighway-armv8/build/highway-1.0.0/hwy/per_target.cc:20:
/home/embybuilder/Buildbot/armv8/libhighway-armv8/build/highway-1.0.0/hwy/ops/arm_sve-inl.h: In function 'svuint64_t hwy::N_SVE_256::CompressBlocksNot(svuint64_t, svbool_t)':
/home/embybuilder/Buildbot/armv8/libhighway-armv8/build/highway-1.0.0/hwy/ops/arm_sve-inl.h:2253:46: warning: conversion to 'size_t' {aka 'long unsigned int'} from 'int' may change the sign of the result [-Wsign-conversion]
 2253 |   const size_t offset = ((bits & 1) ? 4 : 0) + ((bits & 0x10000) ? 8 : 0);
      |                         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
{standard input}: Assembler messages:
{standard input}:22: Error: unknown architectural extension `sve2-aes'
[7/10] Building CXX object CMakeFiles/hwy.dir/hwy/nanobenchmark.cc.o
ninja: build stopped: subcommand failed.
```

Is there a way to get rid of that error? Happy to provide any additional information.

**Comment by jan-wassenberg** [comment]
Hi @alucryd, thanks for reaching out. This is already fixed in trunk and we'll do a release soon, hopefully in the next few days.

**Comment by malaterre** [comment]
@alucryd Just fyi here is the list of local patches I used in Debian against 1.0.0:

* https://salsa.debian.org/debian-phototools-team/highway/-/tree/debian/1.0.0-5/debian/patches

**Comment by alucryd** [comment]
Gave the git HEAD a try, while the warning has been taken care of, unfortunately the error remains:
```
ninja: Entering directory `build'
[1/10] Building CXX object CMakeFiles/hwy.dir/hwy/print.cc.o
[2/10] Building CXX object CMakeFiles/hwy.dir/hwy/targets.cc.o
[3/10] Building CXX object CMakeFiles/hwy.dir/hwy/aligned_allocator.cc.o
[4/10] Building CXX object CMakeFiles/hwy_list_targets.dir/hwy/tests/list_targets.cc.o
[5/10] Building CXX object CMakeFiles/hwy_test.dir/hwy/tests/test_util.cc.o
[6/10] Building CXX object CMakeFiles/hwy.dir/hwy/nanobenchmark.cc.o
[7/10] Building CXX object CMakeFiles/hwy.dir/hwy/per_target.cc.o
FAILED: CMakeFiles/hwy.dir/hwy/per_target.cc.o 
/home/embybuilder/Buildbot/armv8/toolchain/bin/aarch64-emby-linux-gnu-g++ --sysroot=/home/embybuilder/Buildbot/armv8/toolchain/aarch64-emby-linux-gnu/sysroot -DHWY_STATIC_DEFINE -I/home/embybuilder/Buildbot/armv8/libhighway-armv8/build -march=armv8-a -mtune=generic -mno-outline-atomics -Os -pipe -fno-plt -I/home/embybuilder/Buildbot/armv8/staging/include -O3 -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -fmath-errno -fno-exceptions -MD -MT CMakeFiles/hwy.dir/hwy/per_target.cc.o -MF CMakeFiles/hwy.dir/hwy/per_target.cc.o.d -o CMakeFiles/hwy.dir/hwy/per_target.cc.o -c /home/embybuilder/Buildbot/armv8/libhighway-armv8/build/hwy/per_target.cc
{standard input}: Assembler messages:
{standard input}:22: Error: unknown architectural extension `sve2-aes'
ninja: build stopped: subcommand failed.
```

**Comment by jan-wassenberg** [comment]
@alucryd oh, I didn't see the actual error, thank you for pointing to it.
Which GCC is this? I see from the [release notes](https://gcc.gnu.org/gcc-10/changes.html) that v10 adds support for sve2-aes. In detect_targets.h we check `HWY_COMPILER_GCC_ACTUAL < 1000` and if so, SVE2 should be disabled.
(Unless you're defining `HWY_BROKEN_TARGETS` yourself? But I don't see that in your command line.)

Can you check which of the following are true?
```
#if HWY_COMPILER_GCC_ACTUAL && HWY_COMPILER_GCC_ACTUAL < 1000
#error "old gcc"
#endif
#if HWY_ENABLED(HWY_SVE2 | HWY_SVE2_128)
#error "sve2 enabled"
#endif
```

**Comment by alucryd** [comment]
Using GCC 10.3.0 built with crosstool-ng, and I'm not defining `HWY_BROKEN_TARGETS` myself.

According to the GCC release notes, you need to explicitely activate `sve2-aes` using `-march`. However I need my libraries to support virtually anything out there so I'm specifically passing `-march=armv8-a -mtune=generic` to GCC, which explains why it fails. Is there an easy way to disable sve2-aes in highway then? If not I can patch `detects_targets.h` locally.

**Comment by alucryd** [comment]
Don't mind experimenting, but you've lost me there, I'm no C/C++ dev, I usually only build and package them.

Still I tried building the above file, here's what I'm getting:
```
../../toolchain/bin/aarch64-emby-linux-gnu-g++ -I. -Os -march=armv8-a -mtune=generic example.cpp
/tmp/ccbsKn2t.s: Assembler messages:
/tmp/ccbsKn2t.s:31: Error: unknown architectural extension `sve2-aes'
/tmp/ccbsKn2t.s:101: Error: unknown architectural extension `sve2-aes'
```

Interestingly, I can't even specify `+sve2-aes` and that is probably the cause:
```
../../toolchain/bin/aarch64-emby-linux-gnu-g++ -I. -Os -march=armv8-a+sve2-aes -mtune=generic example.cpp
Assembler messages:
Error: unknown architectural extension `sve2-aes'
Error: unrecognized option -march=armv8-a+sve2-aes
```

I'm building the toolchain itself with `-march=armv8-a` too, I guess it effectively disables all other available arches and modifiers? Even trying `-march=armv8.5-a` spits `Error: unknown architecture `armv8.5-a'`.

I'll give `HWY_DISABLED_TARGETS` a try then.

**Comment by jan-wassenberg** [comment]
Thanks, it looks like your toolchain is either built from old (prior to version 10) compiler source code, or other arches are indeed disabled as you say (I don't think -march= has that effect - I think that influences what instructions the compiler binary is allowed to use).

The latter would be more likely influenced by a --target= arg to gcc's configure script.

FYI version 0.15 did not support runtime dispatch, so it would only use sve2-aes if already enabled by the compiler.

I think no code changes are required here for 1.0.1, the issue seems to be in the toolchain and we have a workaround (HWY_DISABLED_TARGETS).

**Comment by alucryd** [comment]
It is definitely built from the official GCC 10.3.0 tarball, all of them are, so I'm not sure what's going on. I need to use an older glibc, and some other older components to be somewhat universal though so that may be part of the equation. In any case using `HWY_DISABLED_TARGETS` works for me so this can definitely be closed. Thanks for your help!
